image: ghcr.io/cirruslabs/flutter:latest

stages:
  - build

variables:
  PUB_CACHE: "${CI_PROJECT_DIR}/.pub-cache"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pub-cache/
    - .gradle/

before_script:
  - export PATH="$PATH:$PUB_CACHE/bin"
  - flutter pub get

build_apk:
  stage: build
  script:
    - flutter build apk --release --split-per-abi

  artifacts:
    name: "VPN-Release-$CI_COMMIT_SHORT_SHA"
    paths:
      - build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
    expire_in: 30 days
  only:
    - main
